## Homework
The goal of this homework is to train a simple model for predicting the duration of a ride - similar to what we did in this module.

## Q1. Downloading the data
We'll use the same NYC taxi dataset, but instead of "Green Taxi Trip Records", we'll use "Yellow Taxi Trip Records".

Download the data for January and February 2023.

Read the data for January. How many columns are there?

- 16
- 17
- 18
- 19

In [1]:
import pandas as pd 
import datetime

In [2]:
df_01 = pd.read_parquet('/Users/pitsuevt/work_main/learning/datatalks/mlops_zoomcamp_2025/01-intro/data/yellow_tripdata_2023-01.parquet')
df_02 = pd.read_parquet('/Users/pitsuevt/work_main/learning/datatalks/mlops_zoomcamp_2025/01-intro/data/yellow_tripdata_2023-02.parquet')

In [3]:
df_01.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), object(1)
memory usage: 444.6+ MB

### Answer:
- 19

## Q2. Computing duration
Now let's compute the duration variable. It should contain the duration of a ride in minutes.

What's the standard deviation of the trips duration in January?

- 32.59
- 42.59
- 52.59
- 62.59

In [5]:
df_01.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
dtype: object

In [6]:
df_01.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

Create new column trip_duration

In [7]:
df_01['trip_duration'] = df_01['tpep_dropoff_datetime'] - df_01['tpep_pickup_datetime']
df_02['trip_duration'] = df_02['tpep_dropoff_datetime'] - df_02['tpep_pickup_datetime']

Apply lambda function to trip_duration column in order to convert timedelta format to minutes

In [8]:
df_01['trip_duration'] = df_01['trip_duration'].apply(lambda x: x.total_seconds()/60)
df_02['trip_duration'] = df_02['trip_duration'].apply(lambda x: x.total_seconds()/60)

In [9]:
df_01

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,trip_duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,8.433333
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,6.316667
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,12.750000
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,9.616667
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,10.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN,13.983333
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN,19.450000
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN,24.516667
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN,13.000000
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN,14.400000

Calculate standart deviation

In [10]:
df_01['trip_duration'].std().round(2)

42.59

### Answer:
- 42.59

## Q3. Dropping outliers
Next, we need to check the distribution of the duration variable. There are some outliers. Let's remove them and keep only the records where the duration was between 1 and 60 minutes (inclusive).

What fraction of the records left after you dropped the outliers?

- 90%
- 92%
- 95%
- 98%

In [11]:
df_01['trip_duration'].describe(percentiles=[0.95,0.98,0.99])

count    3.066766e+06
mean     1.566900e+01
std      4.259435e+01
min     -2.920000e+01
50%      1.151667e+01
95%      3.646667e+01
98%      4.873333e+01
99%      5.725000e+01
max      1.002918e+04
Name: trip_duration, dtype: float64

In [12]:
df_01['trip_duration'].max()

10029.183333333332

In [13]:
df_01['trip_duration'].min()

-29.2

In [14]:
df_01_ = df_01[(df_01['trip_duration'] > 1) & (df_01['trip_duration'] <= 60)]

In [15]:
df_01_['VendorID'].count()/df_01['VendorID'].count() * 100

98.11286547457485

### Answer:
- 98

## Q4. One-hot encoding
Let's apply one-hot encoding to the pickup and dropoff location IDs. We'll use only these two features for our model.

Turn the dataframe into a list of dictionaries (remember to re-cast the ids to strings - otherwise it will label encode them)
Fit a dictionary vectorizer
Get a feature matrix from it
What's the dimensionality of this matrix (number of columns)?

- 2
- 155
- 345
- 515
- 715

In [17]:
df_01_

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,trip_duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,8.433333
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,6.316667
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,12.750000
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,9.616667
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,10.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN,13.983333
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN,19.450000
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN,24.516667
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN,13.000000
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN,14.400000

In [18]:
df_01_.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
trip_duration                   float64
dtype: object

In [19]:
categorical = ['PULocationID', 'DOLocationID']
df_01_[categorical] = df_01_[categorical].astype(str)

/tmp/ipykernel_9353/2029190263.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_01_[categorical] = df_01_[categorical].astype(str)

In [20]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression



from sklearn.metrics import mean_squared_error

In [21]:
dv = DictVectorizer()

Convert dataframe into dictionary

In [22]:
df_01_dict = df_01_[categorical].to_dict(orient='records')
df_01_dict

[{'PULocationID': '161', 'DOLocationID': '141'},
 {'PULocationID': '43', 'DOLocationID': '237'},
 {'PULocationID': '48', 'DOLocationID': '238'},
 {'PULocationID': '138', 'DOLocationID': '7'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '161', 'DOLocationID': '137'},
 {'PULocationID': '239', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '200'},
 {'PULocationID': '164', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '234', 'DOLocationID': '68'},
 {'PULocationID': '79', 'DOLocationID': '264'},
 {'PULocationID': '164', 'DOLocationID': '143'},
 {'PULocationID': '138', 'DOLocationID': '33'},
 {'PULocationID': '33', 'DOLocationID': '61'},
 {'PULocationID': '79', 'DOLocationID': '186'},
 {'PULocationID': '90', 'DOLocationID': '48'},
 {'PULocationID': '113', 'DOLocationID': '255'},
 {'PULocationID': '237', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '229'},
 {'PULocationID': '137', 'DOLocationID': '79'},
 {'PULocationID': '132', 'DOLocationID': '116'},
 {'PULocationID': '163', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '161', 'DOLocationID': '87'},
 {'PULocationID': '68', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '232'},
 {'PULocationID': '43', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '229'},
 {'PULocationID': '170', 'DOLocationID': '75'},
 {'PULocationID': '263', 'DOLocationID': '36'},
 {'PULocationID': '163', 'DOLocationID': '186'},
 {'PULocationID': '161', 'DOLocationID': '107'},
 {'PULocationID': '233', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '75'},
 {'PULocationID': '144', 'DOLocationID': '140'},
 {'PULocationID': '229', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '231'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '170', 'DOLocationID': '43'},
 {'PULocationID': '43', 'DOLocationID': '233'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '162'},
 {'PULocationID': '229', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '224'},
 {'PULocationID': '224', 'DOLocationID': '68'},
 {'PULocationID': '132', 'DOLocationID': '61'},
 {'PULocationID': '236', 'DOLocationID': '236'},
 {'PULocationID': '142', 'DOLocationID': '170'},
 {'PULocationID': '107', 'DOLocationID': '145'},
 {'PULocationID': '164', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '140'},
 {'PULocationID': '43', 'DOLocationID': '125'},
 {'PULocationID': '142', 'DOLocationID': '24'},
 {'PULocationID': '151', 'DOLocationID': '237'},
 {'PULocationID': '236', 'DOLocationID': '43'},
 {'PULocationID': '239', 'DOLocationID': '239'},
 {'PULocationID': '68', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '233'},
 {'PULocationID': '137', 'DOLocationID': '114'},
 {'PULocationID': '163', 'DOLocationID': '225'},
 {'PULocationID': '137', 'DOLocationID': '236'},
 {'PULocationID': '239', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '158'},
 {'PULocationID': '148', 'DOLocationID': '79'},
 {'PULocationID': '148', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '238', 'DOLocationID': '42'},
 {'PULocationID': '107', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '158'},
 {'PULocationID': '238', 'DOLocationID': '238'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '48'},
 {'PULocationID': '141', 'DOLocationID': '140'},
 {'PULocationID': '43', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '261'},
 {'PULocationID': '79', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '232'},
 {'PULocationID': '68', 'DOLocationID': '13'},
 {'PULocationID': '13', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '50'},
 {'PULocationID': '238', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '133'},
 {'PULocationID': '132', 'DOLocationID': '188'},
 {'PULocationID': '132', 'DOLocationID': '149'},
 {'PULocationID': '137', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '229'},
 {'PULocationID': '138', 'DOLocationID': '95'},
 {'PULocationID': '132', 'DOLocationID': '218'},
 {'PULocationID': '264', 'DOLocationID': '186'},
 {'PULocationID': '264', 'DOLocationID': '114'},
 {'PULocationID': '264', 'DOLocationID': '79'},
 {'PULocationID': '264', 'DOLocationID': '239'},
 {'PULocationID': '43', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '261'},
 {'PULocationID': '237', 'DOLocationID': '234'},
 {'PULocationID': '90', 'DOLocationID': '48'},
 {'PULocationID': '125', 'DOLocationID': '231'},
 {'PULocationID': '125', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '238'},
 {'PULocationID': '161', 'DOLocationID': '228'},
 {'PULocationID': '186', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '233'},
 {'PULocationID': '162', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '137'},
 {'PULocationID': '264', 'DOLocationID': '264'},
 {'PULocationID': '264', 'DOLocationID': '137'},
 {'PULocationID': '137', 'DOLocationID': '212'},
 {'PULocationID': '141', 'DOLocationID': '231'},
 {'PULocationID': '239', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '262'},
 {'PULocationID': '236', 'DOLocationID': '79'},
 {'PULocationID': '229', 'DOLocationID': '233'},
 {'PULocationID': '137', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '144'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '166'},
 {'PULocationID': '151', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '137'},
 {'PULocationID': '233', 'DOLocationID': '137'},
 {'PULocationID': '170', 'DOLocationID': '238'},
 {'PULocationID': '233', 'DOLocationID': '229'},
 {'PULocationID': '233', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '164'},
 {'PULocationID': '236', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '7'},
 {'PULocationID': '158', 'DOLocationID': '229'},
 {'PULocationID': '236', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '75'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '79', 'DOLocationID': '234'},
 {'PULocationID': '186', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '112'},
 {'PULocationID': '249', 'DOLocationID': '239'},
 {'PULocationID': '236', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '75'},
 {'PULocationID': '234', 'DOLocationID': '186'},
 {'PULocationID': '246', 'DOLocationID': '13'},
 {'PULocationID': '234', 'DOLocationID': '50'},
 {'PULocationID': '50', 'DOLocationID': '90'},
 {'PULocationID': '107', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '4', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '141', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '262', 'DOLocationID': '43'},
 {'PULocationID': '43', 'DOLocationID': '48'},
 {'PULocationID': '229', 'DOLocationID': '236'},
 {'PULocationID': '43', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '143', 'DOLocationID': '68'},
 {'PULocationID': '132', 'DOLocationID': '25'},
 {'PULocationID': '132', 'DOLocationID': '140'},
 {'PULocationID': '141', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '237'},
 {'PULocationID': '239', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '239'},
 {'PULocationID': '148', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '239'},
 {'PULocationID': '107', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '249'},
 {'PULocationID': '164', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '90'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '234'},
 {'PULocationID': '90', 'DOLocationID': '170'},
 {'PULocationID': '162', 'DOLocationID': '170'},
 {'PULocationID': '142', 'DOLocationID': '43'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '151'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '50', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '33'},
 {'PULocationID': '186', 'DOLocationID': '97'},
 {'PULocationID': '236', 'DOLocationID': '137'},
 {'PULocationID': '107', 'DOLocationID': '162'},
 {'PULocationID': '162', 'DOLocationID': '141'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '232'},
 {'PULocationID': '148', 'DOLocationID': '170'},
 {'PULocationID': '137', 'DOLocationID': '13'},
 {'PULocationID': '170', 'DOLocationID': '113'},
 {'PULocationID': '234', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '148'},
 {'PULocationID': '79', 'DOLocationID': '161'},
 {'PULocationID': '234', 'DOLocationID': '125'},
 {'PULocationID': '211', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '45'},
 {'PULocationID': '231', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '229'},
 {'PULocationID': '162', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '75'},
 {'PULocationID': '43', 'DOLocationID': '48'},
 {'PULocationID': '132', 'DOLocationID': '91'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '48', 'DOLocationID': '246'},
 {'PULocationID': '246', 'DOLocationID': '114'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '132', 'DOLocationID': '265'},
 {'PULocationID': '90', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '48'},
 {'PULocationID': '186', 'DOLocationID': '186'},
 {'PULocationID': '186', 'DOLocationID': '125'},
 {'PULocationID': '125', 'DOLocationID': '97'},
 {'PULocationID': '144', 'DOLocationID': '50'},
 {'PULocationID': '211', 'DOLocationID': '88'},
 {'PULocationID': '87', 'DOLocationID': '13'},
 {'PULocationID': '13', 'DOLocationID': '48'},
 {'PULocationID': '68', 'DOLocationID': '107'},
 {'PULocationID': '142', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '249'},
 {'PULocationID': '158', 'DOLocationID': '48'},
 {'PULocationID': '132', 'DOLocationID': '256'},
 {'PULocationID': '50', 'DOLocationID': '68'},
 {'PULocationID': '114', 'DOLocationID': '239'},
 {'PULocationID': '43', 'DOLocationID': '24'},
 {'PULocationID': '24', 'DOLocationID': '243'},
 {'PULocationID': '137', 'DOLocationID': '141'},
 {'PULocationID': '236', 'DOLocationID': '239'},
 {'PULocationID': '142', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '41'},
 {'PULocationID': '239', 'DOLocationID': '42'},
 {'PULocationID': '41', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '141', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '48'},
 {'PULocationID': '114', 'DOLocationID': '68'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '237', 'DOLocationID': '143'},
 {'PULocationID': '239', 'DOLocationID': '107'},
 {'PULocationID': '186', 'DOLocationID': '229'},
 {'PULocationID': '229', 'DOLocationID': '237'},
 {'PULocationID': '236', 'DOLocationID': '42'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '246', 'DOLocationID': '233'},
 {'PULocationID': '249', 'DOLocationID': '48'},
 {'PULocationID': '246', 'DOLocationID': '61'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '142'},
 {'PULocationID': '161', 'DOLocationID': '229'},
 {'PULocationID': '164', 'DOLocationID': '234'},
 {'PULocationID': '113', 'DOLocationID': '238'},
 {'PULocationID': '142', 'DOLocationID': '41'},
 {'PULocationID': '151', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '114'},
 {'PULocationID': '50', 'DOLocationID': '48'},
 {'PULocationID': '137', 'DOLocationID': '162'},
 {'PULocationID': '233', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '193'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '79'},
 {'PULocationID': '90', 'DOLocationID': '68'},
 {'PULocationID': '249', 'DOLocationID': '148'},
 {'PULocationID': '142', 'DOLocationID': '181'},
 {'PULocationID': '25', 'DOLocationID': '257'},
 {'PULocationID': '164', 'DOLocationID': '90'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '262', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '13'},
 {'PULocationID': '170', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '94'},
 {'PULocationID': '132', 'DOLocationID': '80'},
 {'PULocationID': '107', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '107'},
 {'PULocationID': '170', 'DOLocationID': '195'},
 {'PULocationID': '132', 'DOLocationID': '238'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '237'},
 {'PULocationID': '107', 'DOLocationID': '50'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '142', 'DOLocationID': '231'},
 {'PULocationID': '50', 'DOLocationID': '261'},
 {'PULocationID': '249', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '87'},
 {'PULocationID': '132', 'DOLocationID': '10'},
 {'PULocationID': '234', 'DOLocationID': '87'},
 {'PULocationID': '211', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '255'},
 {'PULocationID': '132', 'DOLocationID': '95'},
 {'PULocationID': '161', 'DOLocationID': '164'},
 {'PULocationID': '170', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '142', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '79', 'DOLocationID': '236'},
 {'PULocationID': '144', 'DOLocationID': '42'},
 {'PULocationID': '238', 'DOLocationID': '167'},
 {'PULocationID': '238', 'DOLocationID': '167'},
 {'PULocationID': '234', 'DOLocationID': '231'},
 {'PULocationID': '144', 'DOLocationID': '263'},
 {'PULocationID': '161', 'DOLocationID': '127'},
 {'PULocationID': '74', 'DOLocationID': '248'},
 {'PULocationID': '142', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '238'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '151'},
 {'PULocationID': '238', 'DOLocationID': '249'},
 {'PULocationID': '48', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '162'},
 {'PULocationID': '141', 'DOLocationID': '89'},
 {'PULocationID': '43', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '262'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '138', 'DOLocationID': '74'},
 {'PULocationID': '263', 'DOLocationID': '239'},
 {'PULocationID': '143', 'DOLocationID': '151'},
 {'PULocationID': '229', 'DOLocationID': '263'},
 {'PULocationID': '141', 'DOLocationID': '229'},
 {'PULocationID': '141', 'DOLocationID': '75'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '263', 'DOLocationID': '145'},
 {'PULocationID': '234', 'DOLocationID': '164'},
 {'PULocationID': '107', 'DOLocationID': '186'},
 {'PULocationID': '238', 'DOLocationID': '151'},
 {'PULocationID': '151', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '107'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '233', 'DOLocationID': '74'},
 {'PULocationID': '263', 'DOLocationID': '233'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '140'},
 {'PULocationID': '237', 'DOLocationID': '161'},
 {'PULocationID': '229', 'DOLocationID': '137'},
 {'PULocationID': '233', 'DOLocationID': '223'},
 {'PULocationID': '143', 'DOLocationID': '166'},
 {'PULocationID': '24', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '141'},
 {'PULocationID': '140', 'DOLocationID': '263'},
 {'PULocationID': '140', 'DOLocationID': '47'},
 {'PULocationID': '163', 'DOLocationID': '107'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '249', 'DOLocationID': '233'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '263'},
 {'PULocationID': '141', 'DOLocationID': '141'},
 {'PULocationID': '264', 'DOLocationID': '263'},
 {'PULocationID': '137', 'DOLocationID': '263'},
 {'PULocationID': '162', 'DOLocationID': '140'},
 {'PULocationID': '164', 'DOLocationID': '229'},
 {'PULocationID': '246', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '246'},
 {'PULocationID': '246', 'DOLocationID': '68'},
 {'PULocationID': '246', 'DOLocationID': '4'},
 {'PULocationID': '246', 'DOLocationID': '151'},
 {'PULocationID': '151', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '137'},
 {'PULocationID': '170', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '140'},
 {'PULocationID': '263', 'DOLocationID': '162'},
 {'PULocationID': '249', 'DOLocationID': '223'},
 {'PULocationID': '146', 'DOLocationID': '145'},
 {'PULocationID': '142', 'DOLocationID': '229'},
 {'PULocationID': '140', 'DOLocationID': '40'},
 {'PULocationID': '231', 'DOLocationID': '164'},
 {'PULocationID': '50', 'DOLocationID': '186'},
 {'PULocationID': '186', 'DOLocationID': '164'},
 {'PULocationID': '170', 'DOLocationID': '237'},
 {'PULocationID': '142', 'DOLocationID': '107'},
 {'PULocationID': '137', 'DOLocationID': '229'},
 {'PULocationID': '50', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '263'},
 {'PULocationID': '166', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '143'},
 {'PULocationID': '234', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '140'},
 {'PULocationID': '141', 'DOLocationID': '107'},
 {'PULocationID': '113', 'DOLocationID': '202'},
 {'PULocationID': '237', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '79'},

In [23]:
X_train = dv.fit_transform(df_01_dict)

In [24]:
X_train

<3008892x515 sparse matrix of type '<class 'numpy.float64'>'
	with 6017784 stored elements in Compressed Sparse Row format>

Try to figure out what's the dimensionality of this matrix

In [25]:
X_train.shape

(3008892, 515)

### Answer:
- 515

## Q5. Training a model
Now let's use the feature matrix from the previous step to train a model.

Train a plain linear regression model with default parameters
Calculate the RMSE of the model on the training data
What's the RMSE on train?

- 3.64
- 7.64
- 11.64
- 16.64

In [26]:
X_train

<3008892x515 sparse matrix of type '<class 'numpy.float64'>'
	with 6017784 stored elements in Compressed Sparse Row format>

Get a target value

In [39]:
y_train = df_01_['trip_duration'].values

In [40]:
df_01_['trip_duration'].max()

60.0

Train a model

In [41]:
lr = LinearRegression()

In [42]:
lr.fit(X_train, y_train)

LinearRegression()

Get a prediction

In [43]:
y_pred = lr.predict(X_train)

Calculate a quality of our model

In [44]:
mean_squared_error(y_train, y_pred, squared=False)

7.648231384745714

### Answer:
- 7.64

## Q6. Evaluating the model
Now let's apply this model to the validation dataset (February 2023).

What's the RMSE on validation?

- 3.81
- 7.81
- 11.81
- 16.81

Validation dataset

Make a functions for prepare data and train model

In [10]:
import pandas as pd 
import datetime

from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
def prepare_data(filename):
    df = pd.read_parquet(filename)
    
    df['trip_duration'] = df['tpep_dropoff_datetime'] - df['tpep_pickup_datetime']
    df['trip_duration'] = df['trip_duration'].apply(lambda x: x.total_seconds()/60)
    
    df = df[(df['trip_duration'] > 1) & (df['trip_duration'] <= 60)]
    
    df['PULocationID'] = df['PULocationID'].astype(str)
    df['DOLocationID'] = df['DOLocationID'].astype(str)
    
    return df

In [3]:
df_01 = prepare_data('/home/timur/work_hub/mlops_zoomcamp_2024/01-intro/data/yellow_tripdata_2023-01.parquet')
df_02 = prepare_data('/home/timur/work_hub/mlops_zoomcamp_2024/01-intro/data/yellow_tripdata_2023-02.parquet')

In [6]:
categorical = ['PULocationID', 'DOLocationID']

dv = DictVectorizer()

train_dicts = df_01[categorical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)

val_dicts = df_02[categorical].to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [7]:
target = 'trip_duration'
y_train = df_01[target].values
y_val = df_02[target].values

In [8]:
lr = LinearRegression()
lr.fit(X_train, y_train)

lr.predict(X_val)

array([11.36825211, 49.69527378, 15.19190156, ..., 13.53323652,
       11.09622451, 13.15765781])

In [9]:
y_pred = lr.predict(X_val)

In [12]:
mean_squared_error(y_val, y_pred, squared=False)

7.810095061511874

### Answer: 
- 7.81